sonic:
  vars:
    domain: sonic.cisco.com
    ansible_become: yes
    ansible_user: cisco
    ansible_ssh_pass: cisco123
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    c1:
      ansible_host: 1.18.1.1
    c2:
      ansible_host: 1.18.1.2
    c3:
      ansible_host: 1.18.1.3
      ansible_user: admin
      ansible_ssh_pass: password
    c4:
      ansible_host: 1.18.1.4
      ansible_user: admin
      ansible_ssh_pass: YourPaSsWoRd
    c8:
      ansible_host: 1.18.1.8
